# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cleaner.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcleaner.proto\x12\x02pb\"\x1c\n\x0c\x43leanRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1d\n\rCleanResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32>\n\x0e\x43leanerService\x12,\n\x05\x43lean\x12\x10.pb.CleanRequest\x1a\x11.pb.CleanResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cleaner_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_CLEANREQUEST']._serialized_start=21
  _globals['_CLEANREQUEST']._serialized_end=49
  _globals['_CLEANRESPONSE']._serialized_start=51
  _globals['_CLEANRESPONSE']._serialized_end=80
  _globals['_CLEANERSERVICE']._serialized_start=82
  _globals['_CLEANERSERVICE']._serialized_end=144
# @@protoc_insertion_point(module_scope)
